/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"github.com/gin-gonic/gin"
)

type PapersAPI interface {

	// PapersFind Get /api/papers/find
	// Find paper
	PapersFind(c *gin.Context)

	// PapersUpdate Post /api/papers/update
	// Update paper
	PapersUpdate(c *gin.Context)
}
