/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// SectionWithoutAutofield - Section object without auto-generated fields
type SectionWithoutAutofield struct {

	// Section name
	Name string `json:"name"`

	// Section content
	Content string `json:"content"`
}
