/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// GraphUpdateResponse - Response Body for Graph Update API
type GraphUpdateResponse struct {
	Graph Graph `json:"graph"`
}
