/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PaperFindResponse - Request Body for Paper Find API
type PaperFindResponse struct {
	Paper Paper `json:"paper"`
}
