/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ChapterWithoutAutofield - Chapter object without auto-generated fields
type ChapterWithoutAutofield struct {

	// Chapter name
	Name string `json:"name"`

	// next chapter ID
	NextId string `json:"nextId"`
}
