/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ProjectOnlyIdError - Error Message for ProjectOnlyId object
type ProjectOnlyIdError struct {

	// Error message for project ID
	Id string `json:"id,omitempty"`
}
