/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ChapterOnlyId - Chapter object with only ID
type ChapterOnlyId struct {

	// Auto-generated chapter ID
	Id string `json:"id"`
}
