/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// GraphChildError - Error Message for GraphChild object
type GraphChildError struct {

	// Error message for graph child name
	Name string `json:"name,omitempty"`

	// Error message for graph child relation
	Relation string `json:"relation,omitempty"`

	// Error message for graph child description
	Description string `json:"description,omitempty"`

	Children GraphChildrenError `json:"children,omitempty"`
}
