/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ChapterError - Error Message for Chapter object
type ChapterError struct {

	// Error message for chapter id
	Id string `json:"id,omitempty"`

	// Error message for chapter name
	Name string `json:"name,omitempty"`

	// Error message for chapter next id
	NextId string `json:"nextId,omitempty"`
}
