/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PaperSectionalizeResponse - Response Body for Paper Sectionalize API
type PaperSectionalizeResponse struct {
	Sections []Section `json:"sections"`
}
