/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ChapterListRequest - Request Body for Chapter List API
type ChapterListRequest struct {
	User UserOnlyId `json:"user"`

	Project ProjectOnlyId `json:"project"`
}
