/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// GraphOnlyIdError - Error Message for GraphOnlyId object
type GraphOnlyIdError struct {

	// Error message for graph ID
	Id string `json:"id,omitempty"`
}
