/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ProjectCreateErrorResponse - Error Response Body for Project Create API
type ProjectCreateErrorResponse struct {

	// Error message when request body format is invalid
	Message string `json:"message,omitempty"`

	User UserOnlyIdError `json:"user,omitempty"`

	Project ProjectWithoutAutofieldError `json:"project,omitempty"`
}
