/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// Section - Section object
type Section struct {

	// Auto-generated section ID
	Id string `json:"id"`

	// Section name
	Name string `json:"name"`
}
