/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PaperWithoutAutofieldError - Error Message for Paper object
type PaperWithoutAutofieldError struct {

	// Error message for paper content
	Content string `json:"content,omitempty"`
}
