/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ChapterCreateResponse - Response Body for Chapter Create API
type ChapterCreateResponse struct {
	Chapter ChapterWithSections `json:"chapter"`
}
