/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ProjectWithoutAutofield - Project object without auto-generated fields
type ProjectWithoutAutofield struct {

	// Project name
	Name string `json:"name"`

	// Project description
	Description string `json:"description,omitempty"`
}
