/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// Paper - Paper object
type Paper struct {

	// Auto-generated paper ID
	Id string `json:"id"`

	// Paper content
	Content string `json:"content"`
}
