/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PaperUpdateRequest - Request Body for Paper Update API
type PaperUpdateRequest struct {
	User UserOnlyId `json:"user"`

	Project ProjectOnlyId `json:"project"`

	Paper Paper `json:"paper"`
}
