/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PaperFindErrorResponse - Request Body for Paper Find API
type PaperFindErrorResponse struct {
	User UserOnlyIdError `json:"user"`

	Project ProjectOnlyIdError `json:"project"`

	Chapter ChapterOnlyIdError `json:"chapter"`
}
