/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ProjectWithoutIdError - Error Message for ProjectWithoutId object
type ProjectWithoutIdError struct {

	// Error message for project name
	Name string `json:"name,omitempty"`

	// Error message for project description
	Description string `json:"description,omitempty"`
}
