/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ProjectWithoutId - Project object without auto-generated ID
type ProjectWithoutId struct {

	// Project name
	Name string `json:"name"`

	// Project description
	Description string `json:"description,omitempty"`
}
