/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ProjectCreateRequest - Request Body for Project Create API
type ProjectCreateRequest struct {
	User UserOnlyId `json:"user"`

	Project ProjectWithoutAutofield `json:"project"`
}
