/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// GraphOnlyId - Graph object with only ID
type GraphOnlyId struct {

	// Auto-generated graph ID
	Id string `json:"id"`
}
