/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// UserError - Error Message for User object
type UserError struct {

	// Error message for user ID
	Id string `json:"id,omitempty"`
}
