/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ProjectUpdateRequest - Request Body for Project Update API
type ProjectUpdateRequest struct {
	User UserOnlyId `json:"user"`

	Project Project `json:"project"`
}
