/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ApplicationSuccessResponse - Common Success response for application
type ApplicationSuccessResponse struct {

	// Success message
	Message string `json:"message"`
}
