/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ProjectListErrorResponse - Error Response Body for Project List API
type ProjectListErrorResponse struct {

	// Error message when request body format is invalid
	Message string `json:"message"`

	// Error message for user ID
	UserId string `json:"userId,omitempty"`
}
