/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PaperOnlyId - Paper object with only ID
type PaperOnlyId struct {

	// Auto-generated paper ID
	Id string `json:"id"`
}
