/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PaperSectionalizeRequest - Request Body for Paper Sectionalize API
type PaperSectionalizeRequest struct {
	User UserOnlyId `json:"user"`

	Project ProjectOnlyId `json:"project"`

	Paper PaperOnlyId `json:"paper"`

	Sections []SectionWithoutAutofield `json:"sections"`
}
