/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type GraphsAPI interface {

	// GraphsDelete Post /api/graphs/delete
	// Delete graph
	GraphsDelete(c *gin.Context)

	// GraphsFind Get /api/graphs/find
	// Find graph
	GraphsFind(c *gin.Context)

	// GraphsSectionalize Post /api/graphs/sectionalize
	// Sectionalize into graphs
	GraphsSectionalize(c *gin.Context)

	// GraphsUpdate Post /api/graphs/update
	// Update graph
	GraphsUpdate(c *gin.Context)
}
