/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GraphDeleteRequest - Request Body for Graph Delete API
type GraphDeleteRequest struct {
	User UserOnlyId `json:"user"`

	Project ProjectOnlyId `json:"project"`

	Chapter ChapterOnlyId `json:"chapter"`

	Section SectionOnlyId `json:"section"`
}
