/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProjectListRequest - Request Parameters for Project List API
type ProjectListRequest struct {

	// User ID
	UserId string `json:"userId" form:"userId"`
}
