/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GraphSectionalizeRequest - Request Body for Graph Sectionalize API
type GraphSectionalizeRequest struct {
	User UserOnlyId `json:"user"`

	Project ProjectOnlyId `json:"project"`

	Chapter ChapterOnlyId `json:"chapter"`

	Sections []SectionWithoutAutofield `json:"sections"`
}
