/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProjectError - Error Message for Project object
type ProjectError struct {

	// Error message for project ID
	Id string `json:"id,omitempty"`

	// Error message for project name
	Name string `json:"name,omitempty"`

	// Error message for project description
	Description string `json:"description,omitempty"`
}
