/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ChapterListRequest - Request Body for Chapter List API
type ChapterListRequest struct {

	// User ID
	UserId string `json:"userId" form:"userId"`

	// Auto-generated project ID
	ProjectId string `json:"projectId" form:"projectId"`
}
