/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PaperWithoutAutofield - Paper object without auto-generated fields
type PaperWithoutAutofield struct {

	// Paper content
	Content string `json:"content"`
}
