/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GraphContentError - Error Message for GraphContent object
type GraphContentError struct {

	// Error message for graph ID
	Id string `json:"id,omitempty"`

	// Error message for graph paragraph
	Paragraph string `json:"paragraph,omitempty"`

	Children GraphChildrenError `json:"children,omitempty"`
}
