/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProjectFindResponse - Response Body for Project Find API
type ProjectFindResponse struct {
	Project Project `json:"project"`
}
