/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Project - Project object
type Project struct {

	// Auto-generated project ID
	Id string `json:"id"`

	// Project name
	Name string `json:"name"`

	// Project description
	Description string `json:"description,omitempty"`
}
