/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProjectUpdateResponse - Response Body for Project Update API
type ProjectUpdateResponse struct {
	Project Project `json:"project"`
}
