/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ChapterOnlyIdError - Error Message for ChapterOnlyId object
type ChapterOnlyIdError struct {

	// Error message for chapter ID
	Id string `json:"id,omitempty"`
}
