/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// UserOnlyId - User object with only ID
type UserOnlyId struct {

	// User ID
	Id string `json:"id"`
}
