/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GraphSectionalizeResponse - Response Body for Graph Sectionalize API
type GraphSectionalizeResponse struct {
	Graphs []Graph `json:"graphs"`
}
