/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProjectListResponse - Response Body for Project List API
type ProjectListResponse struct {
	Projects []Project `json:"projects"`
}
