/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SectionOnlyIdError - Error Message for SectionOnlyId object
type SectionOnlyIdError struct {

	// Error message for section ID
	Id string `json:"id,omitempty"`
}
