/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ChapterUpdateResponse - Response Body for Chapter Update API
type ChapterUpdateResponse struct {
	Chapter ChapterWithSections `json:"chapter"`
}
