/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PaperUpdateResponse - Response Body for Paper Update API
type PaperUpdateResponse struct {
	Paper Paper `json:"paper"`
}
