/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GraphContentWithoutAutofieldError - Error Message for GraphContentWithoutAutofield object
type GraphContentWithoutAutofieldError struct {

	// Error message for graph paragraph
	Paragraph string `json:"paragraph,omitempty"`

	Children GraphChildrenError `json:"children,omitempty"`
}
