/*
 * Web API of kNODEledge
 *
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ChapterWithoutAutofieldError - Error Message for ChapterWithoutAutofield object
type ChapterWithoutAutofieldError struct {

	// Error message for chapter name
	Name string `json:"name,omitempty"`

	// Error message for chapter number
	Number string `json:"number,omitempty"`
}
