name: Push

on:
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
  docstest:
    uses: ./.github/workflows/reusable-docstest.yml
  release:
    needs: [test, docstest]
    uses: ./.github/workflows/reusable-release.yml
