name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Setup dependencies
        run: go get -v ./...

      - name: Setup firesrore emulator
        run: curl -sL https://firebase.tools | bash

      - name: Run go format
        run: make format

      - name: Run go lint
        run: make lint

      - name: Run go build
        run: make build

      - name: Run go test
        run: make generate test
