name: Docs Test

on:
  workflow_call:

jobs:
  docstest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Display Node.js version
        run: node --version

      - name: Install dependencies
        run: yarn global add @redocly/cli

      - name: Run docs build
        run: redocly build-docs docs/openapi/_index.yaml --output tmp/openapi-docs.html
