name: GitHub Pages

on:
  workflow_call:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Display Node.js version
        run: node --version

      - name: Install dependencies
        run: yarn global add @redocly/cli

      - name: Build Open API documentation
        run: redocly build-docs docs/openapi/_index.yaml --output openapi-build/index.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: openapi-build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
