name: Go

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.5]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: make install

      - name: Run go build
        run: make build

      - name: Run go test
        run: make test

  test-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Display Node.js version
        run: node --version

      - name: Install dependencies
        run: yarn global add @redocly/cli

      - name: Run docs build
        run: redocly build-docs docs/openapi/_index.yaml --output tmp/openapi-docs.html
